---
extends: stylelint-config-sass-guidelines
plugins:
  - stylelint-selector-bem-pattern
  - stylelint-scss
rules:
  plugin/selector-bem-pattern:
    preset: suit
    componentName: \w+
    componentSelectors:
      initial: ^\\.{componentName}(?:-[a-z]+)?$
      combined: ^\\.combined-{componentName}-[a-z]+$
    utilitySelectors: ^\\.util-[a-z]+$
  indentation: tab
  string-quotes: single
  no-duplicate-selectors: true
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  selector-combinator-space-after: always
  selector-class-pattern: null
  selector-attribute-quotes: always
  selector-attribute-operator-space-before: never
  selector-attribute-operator-space-after: never
  selector-attribute-brackets-space-inside: never
  declaration-block-trailing-semicolon: always
  declaration-no-important: true
  declaration-colon-space-before: never
  declaration-colon-space-after: always-single-line
  function-url-quotes: never
  font-weight-notation: numeric
  font-family-name-quotes: always-where-recommended
  comment-whitespace-inside: always
  comment-empty-line-before: always
  selector-pseudo-element-colon-notation: double
  selector-pseudo-class-parentheses-space-inside: never
  media-feature-range-operator-space-before: always
  media-feature-range-operator-space-after: always
  media-feature-parentheses-space-inside: never
  media-feature-colon-space-before: never
  media-feature-colon-space-after: always
  no-duplicate-at-import-rules: true
  number-leading-zero: never
  rule-empty-line-before: null
  scss/dollar-variable-colon-space-after: at-least-one-space
  max-nesting-depth: null
  selector-max-compound-selectors: 5
